### ISSUE TITLE
Parts of window are NOT being captured 

### ISSUE THREAD

**Issue by LordTrololo** [robmikh/Win32CaptureSample#18]
I tried Paint, 3DViewer and they all exhibit this behaviour. I uploded the video showing the problem:

![WindowGraphicsCapturer](https://user-images.githubusercontent.com/61494668/90373580-685c6280-e072-11ea-999a-dc6e65492d3a.gif)

As you can see, we don't capture everything, clicking on _Help_ or _View_ doesn't get captured.

Is there some solution to this problem ?

**Comment by robmikh** [comment]
This is something we're tracking and unfortunately don't have a workaround for yet. Applications that utilize pop-ups or other top level windows are not included in the capture since they are technically "outside" the window. We're looking for a solution internally.

**Comment by LordTrololo** [comment]
Ok, thanks for anwser. 

Is there maybe some rough estimate on when could this solution be available, are we in the scope of months or years ?

**Comment by robmikh** [comment]
It's definitely not months (mainly because nothing is 😉), but I can't really give you an estimate. It's a big pain point that we're looking at and take seriously, that's about as much as I can say.

**Comment by LordTrololo** [comment]
Ok. One more question.

I see that _Xbox Game Bar_ suffers from this same problem but _Microsoft Teams_ doesn't suffer from the exhibited behaviour. 
Could you maybe ask your colleagues from Teams department how did they solved it ? I mean I suppose they use the Windws.Graphics.Capture under the hood ?
Its a long shot, but I had to ask...

**Comment by robmikh** [comment]
When I stated there wasn't a workaround, I meant for the UWP Capture API.

As a Win32 only solution, you'll want to look into [PrintWindow ](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-printwindow) and you'll need to identify the correct context menu window to snapshot.

However, that's outside the scope of this sample. I'm closing this issue for now.

**Comment by LordTrololo** [comment]
Has anything changed regarding this problem ?
