### ISSUE TITLE
Capturing File Explorer Window NOT Possible 

### ISSUE THREAD

**Issue by LordTrololo** [robmikh/Win32CaptureSample#19]
It seems that Windows.Graphics.Capture is NOT able to capture any file explorer window. 

This also includes cases when in some XY application one clicks on _Save As_ or _Open File_ and then the file explorer appears.

It seems to me as if the file explorer is a very special beast and not like "normal" applications, it appears to be much more integrated with internal Windows stuff and maybe because of that its not capturable.

Will it ever be capturable (within the Windows.Graphics.Capture API) , is there some work on that field ?

**Comment by robmikh** [comment]
Generally we aim to capture application windows and not dialogs, when it comes to window capture. The shell plays some role in curating the list. Do you have a scenario that requires capturing the file save or open dialogs? 

Also keep in mind that these should still show up in screen captures, they just aren't selectable for window capture.
