### ISSUE TITLE
How can I record the screen or a window and save it to a file?

### ISSUE THREAD

**Issue by wangwenx190** [robmikh/Win32CaptureSample#20]
How can I record the screen or a window and save it to a file? Does it need FFmpeg?

**Comment by robmikh** [comment]
You'll need to take each frame and encode it to the format you desire. FFmpeg is generally a common library used for encoding. You'll have to check the documentation of the encoder you'd like to use. Look for a way to take BGRA8 frames and convert them into something like YUV if you're doing something like H.264.

Here's some projects that take the frames returned by the Capture API and save them as some other format:

- [SimpleRecorder](https://github.com/robmikh/SimpleRecorder) (Encode h.264/mp4)
- [CaptureGifEncoder](https://github.com/robmikh/CaptureGifEncoder) (Encode gif)
- [UWPCaptureGifEncoder](https://github.com/robmikh/UWPCaptureGifEncoder) (Encode gif)

**Comment by wangwenx190** [comment]
Thanks!
