### ISSUE TITLE
Access Violation on GraphicsCaptureSession.IsCursorCaptureEnabled

### ISSUE THREAD

**Issue by LordTrololo** [robmikh/Win32CaptureSample#21]
Using this command results in
` 0xC0000005: Access violation reading location 0x0000000000000000.`

I tried it by adding it in `SimpleCapture.cpp` like so:

```
    m_framePool = winrt::Direct3D11CaptureFramePool::Create(m_device, m_pixelFormat, 2, m_item.Size());
    m_session = m_framePool.CreateCaptureSession(m_item);
    m_session.IsCursorCaptureEnabled(false);                //<------------------------ this doesnt work
    m_lastSize = m_item.Size();
    m_framePool.FrameArrived({ this, &SimpleCapture::OnFrameArrived });
```

Following also give the same exception:
`    auto isCursorCaptureEnabled= m_session.IsCursorCaptureEnabled();  `

**Comment by robmikh** [comment]
I can't reproduce that access violation. Are you running on build 19041 or greater?

**Comment by LordTrololo** [comment]
Yes, I recently switched to 19041 (I think otherwise I couldn't even call the `.IsCursorCaptureEnabled()`).

Thats strange, I will try to debug locally and see if I can find my bug...

**Comment by robmikh** [comment]
I had to check. 🙂 It's possible to install newer SDKs on older builds of Windows, but that will only allow you to compile.

Does this happen every time for you? Could you give this a try on the latest version? I just pushed some updates.

If this does consistently happen, it would be helpful if you could take a [Time Travel Trace](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/time-travel-debugging-overview). Unfortunately I don't have a great solution for where to upload the file.. these dumps can get fairly large.

**Comment by LordTrololo** [comment]
The problem was in my Windows version, it wasn't up to date. So it seems both Windows and Windows SDK have to be up to date for everything to work.

@robmikh  
Thanks for help.
