### ISSUE TITLE
Desktop duplication vs Windows Graphics capture?

### ISSUE THREAD

**Issue by polhaghverdian** [robmikh/Win32CaptureSample#24]
Hi (Barev) @robmikh 

- Is there any differences between Desktop duplication and this API? 

- Using desktop duplication force you to have an monitor plugged into the GPU, in order to capture frames. Is the requirement the same for Windows Graphics capture? So my goal is to use it on a "headless machine".

**Comment by robmikh** [comment]
The Desktop Duplication API (DDA), is only available to traditional Win32 applications. If you wish to capture the screen in a universal application, you'll need to use Windows.Graphics.Capture. With that said, there are some areas where we don't have feature parity quite yet:

- Update rects
  - We do not yet provide this in the API. If this is important to you, it would be great to know as we plan future features. 
- Protected content information
  - We hope to provide this soon, but currently you are not told if we have withdrawn protected content from the frame. This manifests as a black rectangle being substituted for the protected swap chain or window.
- Secure content, like the UAC prompt, can be captured with DDA when you run as the SYSTEM account. This currently isn't available to Windows.Graphics.Capture.

There are advantages over DDA though:

- As mentioned before, UWP support.
- Windows.Graphics.Capture provides per-window capture without having to worry about occlusion.
  - There are still some limitations around applications that decide to stop drawing under certain conditions. For example, many applications stop drawing when they are off-screen, so you would get stale content in that situation.
- In general we avoid an extra copy that can happen with DDA.

As for operating in a headless mode, we can capture monitors that are available to the system. That doesn't necessarily mean a physical monitor, but the system needs to think a monitor is attached. I haven't tried it myself, but you could attempt to use a dummy connector to trick the system into thinking a monitor is attached. Or you could use an [indirect display driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/indirect-display-driver-model-overview) if that better matches your scenario. Basically, if you can enumerate the monitor with [EnumDisplayMonitors](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-enumdisplaymonitors), there's a good chance we can capture it.

That being said, I've never tried to capture a window on a headless machine... part of it will depend on the drawing behavior of the application.

**Comment by polhaghverdian** [comment]
@robmikh Thank you for the great explanation and comparison 👍

**Comment by winstxnhdw** [comment]
> In general we avoid an extra copy that can happen with DDA.

Would this mean that generally, WGC is more performant than DDA?
