### ISSUE TITLE
Capturing Audio

### ISSUE THREAD

**Issue by jamesstringerparsec** [robmikh/Win32CaptureSample#30]
Hey Rob

Thanks for making this sample code, Windows.Graphics.Capture is a very exciting API and I'm eagerly awaiting to see any new updates.

The biggest question I have about this is, from an application capture perspective, is what to do about audio?

Do you know of any method to capture a single applications audio output out side of creating a driver or hooking?

**Comment by robmikh** [comment]
No problem! Let me know if you have any feedback about the capture API.

There isn't a way to do this without hooking (that I know of) on current retail builds of Windows, but I would take a look at the insider builds/SDK for some upcoming APIs. Specifically, I'd look at `audioclientactivationparams.h` 😉. I haven't tried these audio APIs myself yet, as I work on the graphics side of things. I'm looking at version 10.0.20279.1 of the SDK.

https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewSDK

**Comment by jamesstringerparsec** [comment]
Dude! Nice!  If we can start doing application audio capture that will solve 1000000000000 problems (a long with your windows graphics capture stuff) for our app and I'm sure a bunch of other people.  

Thanks man! Have a great weekend.

**Comment by robmikh** [comment]
Looking forward to it!

**Comment by jamesstringerparsec** [comment]
@robmikh Oh and I actually have a question related to your work specifically.

How can we use whatever Xbox Game Bar is using? It seems to be some mix of SetWindowDisplayAffinity and something else (the most recent build simply lets you hide your app from DXGI DD, as well as "print screen" screenshots) but Xbox Game Bar is able to be captured by screenshots but not by our implementation of DXGI Desktop Duplication.  I'm interested in the differences between just blocking our app from capture with SetWindowDisplayAffinity.

**Comment by robmikh** [comment]
I think what you've found are mainly inconsistencies in the OS. Game Bar doesn't seem to use SetWindowDisplayAffinity, mainly because I can still see it when using the Windows.Graphics.Capture API to capture the monitor. The Game Bar is hidden, however, when you capture the game's window as Game Bar has its own window.

Excluding the case of full-screen exclusive applications (where Game Bar doesn't run), DDA and WGC both have their frames rendered by the DWM. All content on the screen is essentially a big Direct Composition tree, and we render starting at a given Visual for both APIs. What's probably happening is that DDA is being rendered with a visual "below" the Game Bar content whereas WGC renders from a visual that is "above" the Game Bar content in the desktop tree (when capturing a monitor). Something similar happens with the print screen functionality.

Is there a particular behavior you're looking to implement?

**Comment by jamesstringerparsec** [comment]
Our application is a screen sharing application, to be used either collaboratively (with someone physically at the device "hosting" and sharing their screen with a guests) or alternatively the app can be used like RDP/VNC etc to connect remotely to a computer.

For the collaboration aspects of the app we would like to be able to draw an overlay on screen of the "host" that contains information about the guests who are joined, their permissions, things like chat messages or maybe a cursor bitmap that indicates where the guest may be using their own mouse to indicate to the "host" user where to look.

For that system to really shine that overlay needs to be visible to the host, who is physically looking at the display, but invisible to either the DDA or WGC capture which is what the guests will see.  We can most likely achieve that in builds of Windows 2004+ and greater with the SetWindowDisplayAffinity function by setting the overlay window to be invisible but I wonder if there is a method for all versions of Windows 10, or at least the versions with Xbox Game Bar type features. 

As for the Windows.Graphics.Capture API I think it is pretty solid, we've not implemented it yet but now there is a chance to capture audio by PID, and you can now omit the cursor from WGC, WGC becomes a whole lot more valuable.  I'd like to see some option to remove the colored boundary of the captured Window, or some way to change the color.  

The last piece of the puzzle is injecting controller inputs into background window.
Often, a situation we run into is where the "host" has a game running (A local multiplayer game for example), and the guests are playing the game with the host (via our software) but the host alt tabs to another application (like a messaging app for example) and at that point since the game window is no longer in focus, the game no longer receives the controller inputs from the guest. We've experimented with solutions but haven't found anything great.
