### ISSUE TITLE
The application crashes when calling IsBorderRequired(false/true)

### ISSUE THREAD

**Issue by nop144d** [robmikh/Win32CaptureSample#40]
After creating the session via `m_session = m_framePool.CreateCaptureSession(m_item);` and setting the border requirement:
`m_session.IsBorderRequired(false);` the application crashes with the following exception

`Exception thrown at 0x00007FF63ACA7E6C in Win32CaptureSample.exe: 0xC0000005: Access violation reading location 0x0000000000000000.`

Is this an API bug or the function should be called somewhere else outside of `SimpleCapture::SimpleCapture()` constructor?

**Comment by robmikh** [comment]
What version of Windows are you attempting this on? The `IsBorderRequired` property was introduced in Windows 11.

**Comment by nop144d** [comment]
I see, I was trying on Windows 10.

**Comment by robmikh** [comment]
You can use the ApiInformation API to see if a given property or object is present at runtime.

**Comment by nop144d** [comment]
an off-topic question: what is the right way to check whether the texture content is changed, so to call CopyResource() not every time, but only when needed. Comparing underlying pointers seems the be an incorrect way as they may be unequal, but the textures could be the same.

**Comment by robmikh** [comment]
Please open a new issue if you have new questions.

Unfortunately, there is no mechanism at this time. To get around this, I use a compute shader. Keep in mind this requires shader model 5. If you'd like an example, [robmikh/CaptureGofEncoder](https://github.com/robmikh/CaptureGifEncoder) demonstrates this technique.

**Comment by nop144d** [comment]
Thank you very much! Will open related issues on the other repo, if any.
