### ISSUE TITLE
Is there any way to keep transparency effect when capturing window?

### ISSUE THREAD

**Issue by Void48** [robmikh/Win32CaptureSample#41]

**Comment by robmikh** [comment]
It depends on what you mean by transparency effects. If you want to preserve the alpha of the window, then yes, window capture should do the trick. Keep in mind that previous version of Windows 10 had a bug where we cleared to black, so it may not work in older versions.

What won't work are effects that texture from what is behind the window, like effects that use a window backdrop brush (e.g. acrylic).
