### ISSUE TITLE
Desktop Duplication API over Remote Desktop in Windows 11

### ISSUE THREAD

**Issue by valinet** [robmikh/Win32CaptureSample#47]
This is not really related to this project per se, but I don't really know where to fill this up; I have learned about this Windows Graphics Capture API only after countless hours of trial and error for getting the older Desktop Duplication API to work over Remote Desktop under Windows 11 (build 22000.856 and 22000.1042). Of course, I have used the [official sample ](https://github.com/microsoftarchive/msdn-code-gallery-microsoft/tree/master/Official%20Windows%20Platform%20Sample/DXGI%20desktop%20duplication%20sample) which works just fine when at the console, as well as in Windows 10, both when at the console and when using remote desktop. I wasn't able to find any mention of the API being deprecated for this use case, so I presume it is a bug introduced by some Windows 11 version? Do you have any insight on this? I'd happily use Windows Graphics Capture, but I need to be able to capture the secure desktop and access the list of updated rectangles.

Thanks for the great tips and awesome project!

**Comment by robmikh** [comment]
I'm glad you've found the project useful!

I'll need to try on recent retail builds, but my DDA test app works fine over RDP on the Win11 builds I have installed. It may be a bug that has since been fixed. Once I get some time next week I can dig a little deeper.

**Comment by valinet** [comment]
Identic report here: https://learn.microsoft.com/en-us/answers/questions/1036445/desktop-duplication-api-doesn39t-work-over-remote.html

**Comment by robmikh** [comment]
Confirmed this is working now.
