### ISSUE TITLE
simplest way for using windows.graphics.capture to take a screenshot (acquire a single frame on demand)

### ISSUE THREAD

**Issue by M-U-X** [robmikh/Win32CaptureSample#50]
Is it possible or even practical to use the windows.graphics.capture to take  single frames (screenshot) of a window on demand, without making a frame pool/session & so on, to capture a screenshot of hardware accelerated windows like most games, since GetDC(hwnd) doesn't work with those, & if it's possible how if it's not too much to ask?

**Comment by robmikh** [comment]
Take a look at [`CaptureSnapshot`](https://github.com/robmikh/Win32CaptureSample/blob/master/Win32CaptureSample/CaptureSnapshot.cpp). There's no way to use Windows.Graphics.Capture without using the frame pool and session. Also note some older games and games that use OpenGL or Vulkan can't be captured when running as truly fullscreen exclusive. For those you'll need to use the [Desktop Duplication API](https://learn.microsoft.com/en-us/windows/win32/direct3ddxgi/desktop-dup-api).
