### ISSUE TITLE
WinSta0\\winlogon failed

### ISSUE THREAD

**Issue by Say-Y** [robmikh/Win32CaptureSample#53]
in WinSta0\\winlogon (Lock screen, ctrl+alt+del screen)

`winrt::Windows::Graphics::Capture::GraphicsCaptureSession::IsSupported();`
`util::CreateCaptureItemForMonitor`

failed

error message: 
combase.dll ~~ ReturnHr(1) tid(xxxx) 8007024 ~service ...
winrt originate error 80040111 :  'Windows.Graphics.Capture.Server.CapturableItem'

but 
`IDXGIOutputDuplication::AcquireNextFrame`

works.

Is there any way to make it work using winrt?

**Comment by robmikh** [comment]
Unfortunately, this is a limitation of Windows.Graphics.Capture vs DDA. WGC requires being part of the interactive session, and is coupled with that session's DWM. At this time if you need to capture the lock screen then your best bet is DDA.
