### ISSUE TITLE
Help: Clarification

### ISSUE THREAD

**Issue by ksmuthucv** [robmikh/Win32CaptureSample#55]
Hello @robmikh,
Lets say we have a screen size of 2x2 (2 columns x 2 rows) or 12x3 (with all the monitors being HD) and there is a full screen window spanned across the entire size of these screen setup(s). Is it fine/possible to capture the full screen window using windows graphics capture api and record? Your feedback is highly appreciated.

Thanks,
Muthu

**Comment by robmikh** [comment]
I think that should work, but there are some caveats. If there are gaps between the monitors, parts of the window may not update in those gaps depending on what the app uses to draw. Secondly, if the window is too big you might run into the max texture size supported by your video card. I'm doubtful you'll hit that second one, but I thought I'd mention it.

**Comment by ksmuthucv** [comment]
Thank you @robmikh
