### ISSUE TITLE
Simple recorder is giving error in WinUI3

### ISSUE THREAD

**Issue by SilentEngineer1999** [robmikh/Win32CaptureSample#56]
I added the code from simplerecord repo to my project when i run its giving error please help. Im using an IDirect3DDevice _device
_framePool = Direct3D11CaptureFramePool.CreateFreeThreaded( _device, DirectXPixelFormat.B8G8R8A8UIntNormalized, 1, size);
System.InvalidCastException: 'Specified cast is not valid. How to write the frames to a video files with a canvas device?

**Comment by robmikh** [comment]
You've already filed the other issue. I have yet to respond because I've been busy.

**Comment by SilentEngineer1999** [comment]
oh i thought i had put it in the wrong repo my bad
