### ISSUE TITLE
The quality of the captured picture is worse than that of the window

### ISSUE THREAD

**Issue by qq88797833** [robmikh/Win32CaptureSample#57]
![image](https://github.com/robmikh/Win32CaptureSample/assets/28855943/d7c6442a-655a-4b09-a211-d7e42032a503)

**Comment by robmikh** [comment]
Keep in mind that the Win32CaptureSample is scaling the content. If you want to do a proper quality comparison, I recommend saving the image raw or with lossless compression and view in your favorite image viewer without any scaling.

**Comment by qq88797833** [comment]
How to set the lossless compression code, thank you very much

**Comment by robmikh** [comment]
You can use the Windows.Graphics.Imaging APIs: https://learn.microsoft.com/en-us/windows/uwp/audio-video-camera/imaging

**Comment by qq88797833** [comment]
hello，This is supposed to save the image, is there a way to change the original image quality when rendering
