### ISSUE TITLE
how to capture child window?

### ISSUE THREAD

**Issue by MemeTao** [robmikh/Win32CaptureSample#58]
I noticed that capturing child window will fail.

**Comment by robmikh** [comment]
If you're attempting to target a child window, then that's not currently supported by Windows.Graphics.Capture. You'll have to use older capturing methods to get those. However, child windows should be captured if you target the top level window.

Note that windows like menus and other popups are not child windows but actually top level windows. Windows.Graphics.Capture does not include these currently. That's something on our radar, but that's all I can say at this time.
