### ISSUE TITLE
The performance overhead of capturing the desktop is too high.

### ISSUE THREAD

**Issue by MemeTao** [robmikh/Win32CaptureSample#60]
4k, 60hz

GPU 3D overhead: 

1. dxgi， 2%
2. wgc,   20-30%

**Comment by robmikh** [comment]
Without a repro this would be hard to track down. Additionally, in earlier versions of Windows, WGC would send frames even when nothing changed in the targeted visual tree. This has been improved in Windows 11 and could account for some of the difference if it caused your test app to do more work. But generally DDA and WGC are both rendered by the DWM.

I'm going to close this for now, but it would be helpful to know what build of Windows you're running, your GPU(s), and what you're using to test.

**Comment by MemeTao** [comment]
There is really exist a huge performance issue on my PC:
![image](https://github.com/robmikh/Win32CaptureSample/assets/26571525/bd459173-2151-4a76-8ba7-789b64a2b443)

here is a simple demo for test:  https://github.com/MemeTao/desktop-capturer (switch dxgi or wgc on "main.cpp::22")


and I checked it using obs too.
