### ISSUE TITLE
Possible Problem With Some Apps

### ISSUE THREAD

**Issue by NiiightmareXD** [robmikh/Win32CaptureSample#62]
This may not be an issue because it will automatically fix and invoke Recreate. Still, the first frame you receive is almost always the incorrect size in some apps. You have to Recreate even if the window size didn't change. For example, when I want to capture VSCode when it is maximized (it's okay when it's not), the first size is 1936x1048, and my display is 1920x1080, so how is the width even 1936 in the first frame? But it was all fixed after Recreate.

It doesn't cause any problems because you Recreate after a size change but it might be a indicator of something else

**Comment by robmikh** [comment]
This has improved in Windows 11, and future updates should also make this better. The issue arises from a disconnect between the Size property on the GraphicsCaptureItem and the ContentSize property from the Direct3D11CaptureFrame. The former on Windows 10 came from win32k, which matches the GetWindowRect API which can include the invisible border around a window. On Windows 11, this now comes from the compositor (under the covers it now calls DwmGetWindowAttribute with DWMWA_EXTENDED_FRAME_BOUNDS), which matches the visual size of the window.

Maximized windows are a slightly different beast, as they sometimes poke outside the window for historical reasons (back when windows had thicker borders). I'm fairly certain there was a bug that was fixed around window size reporting in the maximized case, but I don't remember what release that fix shipped in. I'll double check that it is fixed for upcoming releases.

For the immediate term, there are some things you can do to work around it. They stem from the fact that you can size the frame pool however you want, using the GraphicsCaptureItem's Size is just a convention. First, on Windows 10 you can use DwmGetWindowAttribute to determine the size of a window. For maximized windows (you can test this with the IsZoomed API), 
you can query the monitor's work area which should match the visual size of the window.
