### ISSUE TITLE
How to convert Bgra to Rgba

### ISSUE THREAD

**Issue by NiiightmareXD** [robmikh/Win32CaptureSample#63]
Is it possible to convert bgra to rgba or can I just use DirectXPixelFormat::R8G8B8A8UIntNormalized?

**Comment by robmikh** [comment]
You can use RGBA8 with the capture API. You can try it out in the sample by adding this line in SampleWindow.cpp:

```cpp
    m_pixelFormats = 
    {
        { L"B8G8R8A8UIntNormalized", winrt::DirectXPixelFormat::B8G8R8A8UIntNormalized },
        { L"R16G16B16A16Float", winrt::DirectXPixelFormat::R16G16B16A16Float },
        // This is the new line
        { L"R8G8B8A8UIntNormalized", winrt::DirectXPixelFormat::R8G8B8A8UIntNormalized },
    };
```

You could technically swizzle the pixels in a shader but I'd just set the pixel format in the frame pool.
