### ISSUE TITLE
check_hresult(WINRT_IMPL_SHIM(winrt::Windows::Graphics::Capture::IDirect3D11CaptureFramePoolStatics)->Create(*(void**)(&device), static_cast<int32_t>(pixelFormat), numberOfBuffers, impl::bind_in(size), &result));

### ISSUE THREAD

**Issue by rlewkowicz** [robmikh/Win32CaptureSample#68]
This isn't an issue with your code, I don't know where else to ask stuff like this. I'm trying to make a simple console app that converts frames into an opencv mat. 

I'm getting this error:
```
Exception thrown at 0x00007FFBF9D6D4C5 (GraphicsCapture.dll) in screen-cap-console.exe: 0xC0000005: Access violation reading location 0x0000000000000000.
```

I've tried various takes on this and I'm getting access violations here:
```
    // I've tried various ways to get the first monitor. Idk, if this is even right. Nothing seems to work here.
    const POINT ptZero = { 0, 0 };
    auto hPrimaryMonitor = MonitorFromPoint(ptZero, MONITOR_DEFAULTTOPRIMARY);

    auto captureInterop = winrt::get_activation_factory<
        winrt::GraphicsCaptureItem,
        IGraphicsCaptureItemInterop>();

    winrt::GraphicsCaptureItem item = nullptr;

    winrt::check_hresult(captureInterop->CreateForMonitor(
        hPrimaryMonitor,
        winrt::guid_of<winrt::GraphicsCaptureItem>(),
        winrt::put_abi(item)));

    // this is a modified version of yours and various examples out there. 
    auto d3dDevice = CreateD3DDevice();

    auto pixelFormat = winrt::Windows::Graphics::DirectX::DirectXPixelFormat::R8G8B8A8UIntNormalized;

    auto itemSize = item.Size();

    auto m_framePool = winrt::Direct3D11CaptureFramePool::Create(d3dDevice, pixelFormat, 2, itemSize);
```

It's something to do with the abi. I know they're like some sort of abstract thing and not a real object. 

I have a small rant from here you can ignore

I think a lot of frustrations are even at myself. I fawn over people like you and chuck walbourn. Unfortunately I'm just smart enough to realize how incapable I am in the shadow of gods. 

Given this pretext of understood inadequacy, I'd like to express my frustration at c++ on windows.  There's all these new fancy features, com pointers, language reflection blah blah. If there's anything GNU gets right it's "do one thing, and do it well". I don't need c++ features so I can use other languages, I need c++ libraries so c++ doesn't suck to use. 

I want to take whats on my screen and act upon it. I feel like that's a super simple, generic use case, that lots of people have a need for. I want to be able to say "one current screen object plz" and get one current screen object. Is that selfish? I can't even get monitor0 without doing goofy stuff. Even the most basic, opensource, grassroots projects on the planet usually can give you something like `monitor[0]`. I just wish from one of the largest most prolific institution on the planet I could have the same ease of use. 

I don't think I've ever seen an example that doesn't use R8G8B8A8UIntNormalized. Why do I have to feed this? I want MS to pick the standard and tell me what they chose, I'll tell the next thing. 

As a guy with a career that is an infinite departure from this language and architecture maybe this just isn't for me. I just wish there was enough usability for me to be a weekend c++ warrior.

**Comment by robmikh** [comment]
Unfortunately, I'm unable to reproduce the issue. Your code works fine for me, assuming your version of `CreateD3DDevice` returns a valid `IDirect3DDevice`. I've modified that part to use robmikh.common:

```cpp
#include <robmikh.common/d3dHelpers.h>
#include <robmikh.common/direct3d11.interop.h>

namespace util
{
    using namespace robmikh::common::uwp;
}

auto d3dDevice = util::CreateD3DDevice();
auto device = CreateDirect3DDevice(d3dDevice.as<IDXGIDevice>().get());

// ...

auto framePool = winrt::Direct3D11CaptureFramePool::Create(device, pixelFormat, 2, itemSize);
```

Do you have a complete minimal repro I could look at? I'm assuming the Win32CaptureSample works on the same machine?

**Comment by rlewkowicz** [comment]
I'm so burned out on this. I'll try to put something together. The problem with your libs is that as a console app, it doesn't compile. 

It complains about a whole lot of stuff being undefined. I wanted to put together a main.cpp, without a million header files, that is a very simple start to finish all in one example. 

I even tried to build this: https://github.com/microsoft/PowerToys/tree/main/src/modules/MeasureTool/MeasureToolCore via pulling files into my env. I meticulously got intelligent to at least not complain. But it wont compile. 

What a nightmare. Somehow that project has it use c++ 20, but then core complains about things that got deprecated in 17. It could be that I'm trying to build a console app, but who knows! It's a slog of convoluted examples, none of which represent a simple configuration of its parts. I can't even get to the need or concept of multi threading, because I can't deconstruct these examples into their core parts in any fashion.

Just even trying trying to read code and understand what namespace something comes from. What namespace is iinspectable in, windows foundation of course. How do I know that, chatgpt told me. You wouldn't know that looking here:
https://learn.microsoft.com/en-us/windows/win32/api/inspectable/nn-inspectable-iinspectable

It hallucinates stuff half the time so you get lucky here and there but heaven forbid the actual docs tell you the namespace. I'm sure I could go dig in header files too, but where are those. Again, all over the place! 

I am not an ace dev, I get that. But this is the absolute worst developer experience of any language and system I've had in my life.

**Comment by robmikh** [comment]
I'm not sure what you mean by they don't work in a console app. I have several console apps that use them. If you're trying to use an API without linking the appropriate lib or including the appropriate header, I'm not sure what to tell you.

You're free to ask questions, but adding superfluous rants about other projects you come across isn't helpful.

**Comment by robmikh** [comment]
Here's a console app that takes a screenshot of the primary monitor using Windows.Graphics.Capture and feeding that image into OpenCV. I'm not familiar with OpenCV, so I used the [contours2 demo](https://docs.opencv.org/3.4/da/d32/samples_2cpp_2contours2_8cpp-example.html). You can find the repo here: https://github.com/robmikh/WGCOpenCVInterop

Because I use Visual Studio, I used [vcpkg](https://github.com/microsoft/vcpkg) to generate a Nuget package containing the necessary binaries, libs, and headers needed. There are more details in the README, but you can also replace the Nuget package with whatever way you're used to consuming OpenCV. Additionally I used the header-only library [WIL](https://github.com/microsoft/wil) for an RAII wrapper around an event, but feel free to remove that and use your own implementation.
