### ISSUE TITLE
How to copy the captured frame data to CUDA directly without copy to CPU first?

### ISSUE THREAD

**Issue by GF-Huang** [robmikh/Win32CaptureSample#70]
I had try [`cudaGraphicsD3D11RegisterResource`](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__D3D11.html#group__CUDART__D3D11) but got either [`cudaErrorInvalidDevice`](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038:~:text=installed%20CUDA%20driver.-,cudaErrorInvalidDevice,-%3D%20101) or memory access violation. Could you give some suggestions?

**Comment by robmikh** [comment]
Unfortunately, I can't really provide much guidance here. I don't know much about CUDA. Some things to consider:

- Make sure your D3D device is on the same adapter as where your CUDA code will execute.
- Unless you can retrieve a D3D device from a CUDA object, you'll likely need to use shared textures.
- Are you able to get a texture from a CUDA object? It might be easier to do a video memory copy (CopyResource or CopySubresourceRegion) than to insert an outside texture into CUDA.

I'm going to close this, as CUDA is far outside the scope of this sample.
