### ISSUE TITLE
additional requirement

### ISSUE THREAD

**Issue by lq709708490** [robmikh/Win32CaptureSample#72]
Dear   robmikh

Thanks for a great project. Can you add a pop-up screenshot of the window ? such as Menu pop-ups and pop-up windows. I've used many methods and can only achieve a window screenshot, but it's not possible to intercept the popups together.      Do you have any good ideas please?   

extremely grateful

**Comment by robmikh** [comment]
Currently the capture API only captures the top level window. This is something that will be addressed in a future version of Windows.

For previous versions of Windows you'll need to compose the images yourself after capturing pop-ups with something like PrintWindow. That's outside the scope of this sample.
