### ISSUE TITLE
Add Windows 26100 features

### ISSUE THREAD

**Issue by robmikh** [robmikh/Win32CaptureSample#75]
Here are some features added in 26100 that need to be added to Win32CaptureSample. I may decide that some of these should have their own demos instead of being integrated here:

- [x] [IncludeSecondaryWindows](https://learn.microsoft.com/en-us/uwp/api/windows.graphics.capture.graphicscapturesession.includesecondarywindows?view=winrt-insider) (f11a6b8b0b7603c207aa119370b7adc6233038d3)
- [x] [MinUpdateInterval](https://learn.microsoft.com/en-us/uwp/api/windows.graphics.capture.graphicscapturesession.minupdateinterval?view=winrt-insider) (0264bc66defde5ebb7d1859e4b32bef42e6c3baa)
- [x] [Dirty Region Modes](https://learn.microsoft.com/en-us/uwp/api/windows.graphics.capture.graphicscapturesession.dirtyregionmode?view=winrt-insider) (639597fe9a87ad868b45588323b606d2e26dc0a8)
- [x] [Dirty Regions Visualization](https://learn.microsoft.com/en-us/uwp/api/windows.graphics.capture.direct3d11captureframe.dirtyregions?view=winrt-insider) (0995fbb264cb12532c5d1b8c75736625c0eb41a1)
- [x] IWindowGraphicsCaptureItemInterop (f11a6b8b0b7603c207aa119370b7adc6233038d3)
- [ ] IMonitorGraphicsCaptureItemInterop
- [x] Update SDK references in the README (c18a20fd91ee6819d06b82e901a39ab326975adb)

After all features have been added/evaluated, a new release should be created. That's currently blocked on https://github.com/robmikh/Win32CaptureSample/issues/74

**Comment by robmikh** [comment]
I feel like MinUpdateInterval would be better suited for [CaptureGifEncoder](https://github.com/robmikh/CaptureGifEncoder) or one of the video encoder projects.

**Comment by SGKalugerov** [comment]
Hi,
Could you introduce some methods for saving the captured frame as a image file? Bmp or whatever.
Supposedly, I've started the capturing for an item from HWND, but can't really utilize the frames.
I am looking to grab a BMP if possible.
Regards

**Comment by robmikh** [comment]
Found a workaround for #74
