### ISSUE TITLE
Win32CaptureSample crashes on 24H2 when you click Border Required

### ISSUE THREAD

**Issue by mikeh926** [robmikh/Win32CaptureSample#85]
The sample code works great on Windows 10 22H2 and Windows 11 23H2. I complied with VS2022 17.11.2 SDK 26100.

If I run the same binary on Windows 11 24H2 I can choose a display to capture and capture starts. If I then click on "Border Required" the sample terminates. Debugging shows that it's throwing an exception inside the call to IGraphicsCaptureSession3::put_IsBorderRequired(). All the other functionality new to 24H2 such as damage regions work fine. I have tried it on 2 seperate 24H2 PC's.

I can't see anything obvious wrong with the sample code, but the templates used to implement the winrt language projection makes debugging difficult.

**Comment by robmikh** [comment]
Can you provide your full build number? I'm unable to repro this on a couple of machines.

**Comment by mikeh926** [comment]
Hi, I am running 24H2 build 26100.2314.   A collegue also downloaded and complied the sample and replicated on build 26120.2415.

I suspect this may be a compiler or SDK issue. I have my own project that calls IsBorderRequired() and that works fine on 24H2 so I don't think it's a problem with the API. However my project is compliled with VS2017. It also uses CreateFreeThreaded instead of having a DispatcherQueue.  I tried compling the sample code with older platform toolsets but I am getting odd linker errors. 

Further debugging through the assembler shows that the exception is coming from the call to _guard_dispatch_icall(), which is something to do with Control Flow Guard. I tried turning that off in the compiler settings, but the generated code still contains that call.

Steps to replicate are:
1. Download the latest VS2022.
2. Download the source code
3. Compile using the default settings
4. Run.

Best Regards,
Mike.

**Comment by robmikh** [comment]
Can you reproduce this with the binary provided in the releases section of this repo?

**Comment by robmikh** [comment]
Tried this on 24H2 build 26100.2314 with the prebuilt release binary and couldn't repro. Updating Visual Studio to see if building it locally makes a difference...

One thing to note is that Win32CaptureSample doesn't reference the Windows SDK like it used to, it instead gets a reference through Nuget. I had to do this because GitHub had yet (and maybe still hasn't?) updated the version of the SDK they use on the machines that run GitHub Actions.

**Comment by mikeh926** [comment]
I cannot reproduce using the provided binaries, so it looks like a problem with my build environment. I tried removed the nuget versions of the sdk and winrt stuff and used my locally installed 26100 SDK instead, but still have the same problem. I have no idea why it's only IsBorderRequired() that crashes, is there anything different in the way that is declared in the SDK?

**Comment by robmikh** [comment]
Nope, it should be the same as everything else. I'd attempt to update VS and try again. If it still repros then you may want to contact the VS folks.
