### ISSUE TITLE
"specified service does not exist" when running on the logon screen.

### ISSUE THREAD

**Issue by mikeh926** [robmikh/Win32CaptureSample#86]
Hi,
I have the Capture API working nicely on the users desktop. It also works nicely with the secure desktop.

When launched on the logon screen (before the user has logged on), the call to CreateForMonitor() returns 0x80070424.

Debug Output:
Exception thrown at 0x76BF9C84 (KernelBase.dll) in capture.exe: WinRT originate error - 0x80040111 : 'Windows.Graphics.Capture.Server.CapturableItem'.
GraphicsCapture.dll!687B564D: LogHr(1) tid(ce4) 80070424 The specified service does not exist as an installed service.

To launch on the logon, I have a session 0 service that is using CreateProcessAsUser() to launch my exe and attach it to the logon desktop (WinSta0\Winlogon).  The capture process runs under the same SYSTEM user account that win_logon.exe is running as and is able to show windows and do normal interaction on the logon desktop. 

I suspect this is to do with the CaptureSevice service which is a per-user service so is probably failing to start.

Is there something I can do to get it working on the logon screen? 

Thanks,
Mike.

**Comment by robmikh** [comment]
Unfortunately, no there's not something you do. This is an area where there's still a gap with DDA.
